package accord

var (
	DefaultServer = "localhost:50051"
	// this is used for webflow authentication
	// this ClientID is public so that the server can validate the access token
	// to have been generated by the same clientID
	// this should be added at compile time by the build system when the binary is made
	defaultClientID     = "{{ClientID to be filled in at build time}}"
	defaultClientSecret = "{{ Client Secret to be filled in at build time}}"
	ClientID            = defaultClientID
	ClientSecret        = defaultClientSecret
)
